create table project (
                         id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                         project_name varchar(100) NOT NULL,
                         main_project_id int REFERENCES PROJECT(ID) ON DELETE SET NULL
);

create table usr (
                     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                     username varchar(100) not null,
                     password varchar(100),
                     role varchar(100) not null
);

create table task (
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY  ,
                      task_name varchar(100),
                      task_status varchar NOT NULL ,
                      task_type varchar NOT NULL ,
                      created_at timestamp,
                      status_changed_at timestamp,
                      information varchar(5000),
                      project_id int REFERENCES PROJECT(id) ON DELETE CASCADE ,
                      usr_id int REFERENCES USR(id) on delete SET NULL
);

insert into USR (username, password, role) values ('admin', 'password', 'ROLE_ADMIN');
insert into USR (username, password, role) values ('user', 'password', 'ROLE_USER');